# Generated by Django 5.2.7 on 2026-03-22 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                (
                    "summary",
                    models.CharField(blank=True, max_length=240, verbose_name="摘要"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="发布状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "category",
                    models.CharField(
                        default="general", max_length=50, verbose_name="类型"
                    ),
                ),
                ("message", models.TextField(verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待处理"),
                            ("reviewing", "处理中"),
                            ("resolved", "已完成"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈",
                "verbose_name_plural": "反馈",
                "ordering": ["-created_at"],
            },
        ),
    ]
